### ISSUE TITLE
Summary rating function does not return correct rating

### ISSUE THREAD

**Issue by htuna07** [idriska/spica-taxi-asset#1]
@idriska 
Inside of summaryRating function, the first query that is supposed to filter ratings that are made for the requested user returns all ratings without filtering them. 
`    let ratingsData = await Bucket.data.getAll(TAXI_RATING_BUCKET, {queryParams: {
        rating_to: req.query.id
 }});` 
 should be like this
 `let ratingsData = await Bucket.data.getAll(TAXI_RATING_BUCKET, {queryParams: {
      filter: { rating_to: req.query.id }
 }});`
 to prevent this behavior.

**Comment by idriska** [comment]
@htuna07 Thank you for the feedback
Fixed in 85ae600
